In [3]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time
from bs4 import BeautifulSoup

In [5]:
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get("https://www.google.com")
print(driver.title)
driver.quit()

KeyboardInterrupt:

In [4]:
driver=webdriver.Chrome(service=Service(ChromeDriverManager().install()))

KeyboardInterrupt:

In [10]:
#pagination
alljobs=[]
for page in range(2,11):
    url=f"https://www.naukri.com/data-scientist-jobs-{page}?k=data%20scientist&nignbevent_src=jobsearchDeskGNB"
    driver.get(url)
    print("="*50)
    print(f"Currently scraping Page {page}")
    print(driver.current_url)
    print(soup.title)
    time.sleep(3)
    print(driver.title)
    print(driver.page_source[:500])
    soup=BeautifulSoup(driver.page_source,'html.parser')
    container=soup.find('div',id='listContainer')
    jobs=container.find_all('div',class_='srp-jobtuple-wrapper')
    for job in jobs:
        try:
            title = job.find('a', class_='title').text.strip()
            comp = job.find('a', class_='comp-name mw-25').text.strip()
            rating = job.find('a', class_='rating').text.strip()
            exp = job.find('span', class_='exp-wrap').text.strip()
            loc = job.find('span', class_='loc-wrap ver-line').text.strip()
            description = job.find(
            'span',
            class_='job-desc ni-job-tuple-icon ni-job-tuple-icon-srp-description'
            ).text.strip()

            skills = job.find_all('li', class_='dot-gt tag-li')
            skills_tag = [skill.text.strip() for skill in skills]

            alljobs.append({
            "title": title,
            "company": comp,
            "rating": rating,
            "experience": exp,
            "location": loc,
            "description": description,
            "skills": skills_tag
            })

        except Exception:
            continue

==================================================
Currently scraping Page 2
https://www.naukri.com/data-scientist-jobs-2?k=data%20scientist&nignbevent_src=jobsearchDeskGNB
<title>Page 3 - Data Scientist Jobs - 21525 Data Scientist Job Vacancies In August 2026 - Naukri.com</title>
Page 2 - Data Scientist Jobs - 21523 Data Scientist Job Vacancies In August 2026 - Naukri.com
<html lang="en"><head><meta charset="utf-8"><link rel="dns-prefetch" href="https://www.googletagmanager.com"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/dc3b8c4d86e650ea.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/9216356713d51a36.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/78d41feaba858687.css" data-precedence="next"><link rel="st
==================================================
Currently scraping Page 3
https://www.naukri.com/data-scientist-jobs-3?k=data%20scientist&nignbevent_src=jobsearchDeskGNB
<title>Page 2 - Data Scientist Jobs - 21523 Data Scientist Job Vacancies In August 2026 - Naukri.com</title>
Page 3 - Data Scientist Jobs - 21523 Data Scientist Job Vacancies In August 2026 - Naukri.com
<html lang="en"><head><meta charset="utf-8"><link rel="dns-prefetch" href="https://www.googletagmanager.com"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/dc3b8c4d86e650ea.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/9216356713d51a36.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/78d41feaba858687.css" data-precedence="next"><link rel="st
==================================================
Currently scraping Page 4
https://www.naukri.com/data-scientist-jobs-4?k=data%20scientist&nignbevent_src=jobsearchDeskGNB
<title>Page 3 - Data Scientist Jobs - 21523 Data Scientist Job Vacancies In August 2026 - Naukri.com</title>
Page 4 - Data Scientist Jobs - 21523 Data Scientist Job Vacancies In August 2026 - Naukri.com
<html lang="en"><head><meta charset="utf-8"><link rel="dns-prefetch" href="https://www.googletagmanager.com"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/dc3b8c4d86e650ea.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/9216356713d51a36.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/78d41feaba858687.css" data-precedence="next"><link rel="st
==================================================
Currently scraping Page 5
https://www.naukri.com/data-scientist-jobs-5?k=data%20scientist&nignbevent_src=jobsearchDeskGNB
<title>Page 4 - Data Scientist Jobs - 21523 Data Scientist Job Vacancies In August 2026 - Naukri.com</title>
Page 5 - Data Scientist Jobs - 21524 Data Scientist Job Vacancies In August 2026 - Naukri.com
<html lang="en"><head><meta charset="utf-8"><link rel="dns-prefetch" href="https://www.googletagmanager.com"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/dc3b8c4d86e650ea.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/9216356713d51a36.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/78d41feaba858687.css" data-precedence="next"><link rel="st
==================================================
Currently scraping Page 6
https://www.naukri.com/data-scientist-jobs-6?k=data%20scientist&nignbevent_src=jobsearchDeskGNB
<title>Page 5 - Data Scientist Jobs - 21524 Data Scientist Job Vacancies In August 2026 - Naukri.com</title>
Page 6 - Data Scientist Jobs - 21525 Data Scientist Job Vacancies In August 2026 - Naukri.com
<html lang="en"><head><meta charset="utf-8"><link rel="dns-prefetch" href="https://www.googletagmanager.com"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/dc3b8c4d86e650ea.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/9216356713d51a36.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/78d41feaba858687.css" data-precedence="next"><link rel="st
==================================================
Currently scraping Page 7
https://www.naukri.com/data-scientist-jobs-7?k=data%20scientist&nignbevent_src=jobsearchDeskGNB
<title>Page 6 - Data Scientist Jobs - 21525 Data Scientist Job Vacancies In August 2026 - Naukri.com</title>
Page 7 - Data Scientist Jobs - 21526 Data Scientist Job Vacancies In August 2026 - Naukri.com
<html lang="en"><head><meta charset="utf-8"><link rel="dns-prefetch" href="https://www.googletagmanager.com"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/dc3b8c4d86e650ea.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/9216356713d51a36.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/78d41feaba858687.css" data-precedence="next"><link rel="st
==================================================
Currently scraping Page 8
https://www.naukri.com/data-scientist-jobs-8?k=data%20scientist&nignbevent_src=jobsearchDeskGNB
<title>Page 7 - Data Scientist Jobs - 21526 Data Scientist Job Vacancies In August 2026 - Naukri.com</title>
Page 8 - Data Scientist Jobs - 719 Data Scientist Job Vacancies In August 2026 - Naukri.com
<html lang="en"><head><meta charset="utf-8"><link rel="dns-prefetch" href="https://www.googletagmanager.com"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/dc3b8c4d86e650ea.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/9216356713d51a36.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/78d41feaba858687.css" data-precedence="next"><link rel="st
==================================================
Currently scraping Page 9
https://www.naukri.com/data-scientist-jobs-9?k=data%20scientist&nignbevent_src=jobsearchDeskGNB
<title>Page 8 - Data Scientist Jobs - 719 Data Scientist Job Vacancies In August 2026 - Naukri.com</title>
Page 9 - Data Scientist Jobs - 21526 Data Scientist Job Vacancies In August 2026 - Naukri.com
<html lang="en"><head><meta charset="utf-8"><link rel="dns-prefetch" href="https://www.googletagmanager.com"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/dc3b8c4d86e650ea.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/9216356713d51a36.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/78d41feaba858687.css" data-precedence="next"><link rel="st
==================================================
Currently scraping Page 10
https://www.naukri.com/data-scientist-jobs-10?k=data%20scientist&nignbevent_src=jobsearchDeskGNB
<title>Page 9 - Data Scientist Jobs - 21526 Data Scientist Job Vacancies In August 2026 - Naukri.com</title>
Page 10 - Data Scientist Jobs - 21526 Data Scientist Job Vacancies In August 2026 - Naukri.com
<html lang="en"><head><meta charset="utf-8"><link rel="dns-prefetch" href="https://www.googletagmanager.com"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/dc3b8c4d86e650ea.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/9216356713d51a36.css" data-precedence="next"><link rel="stylesheet" href="https://static.naukimg.com/s/9/121/_next/static/css/78d41feaba858687.css" data-precedence="next"><link rel="st

In [11]:
import pandas as pd
df=pd.DataFrame(alljobs)

In [12]:
df.head(16)

,title,company,rating,experience,location,description,skills
0,Data Scientist,Kotak Mahindra Bank,3.6,3-7 Yrs,"Mumbai, Bengaluru",Skill requirements: . Masters or Bachelor s De...,"[SAS, Machine Learning, Analytics, Python, SQL..."
1,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Chennai,Experience in developing and deploying AI / Ge...,"[Data Science, Artificial Intelligence, Machin..."
2,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Chennai,Roles and ResponsibilitiesDesign and develop d...,"[Data Science, Artificial Intelligence, Machin..."
3,Data Scientist-Artificial Intelligence,IBM,3.9,3-5 Yrs,Kolkata,Your role and responsibilitiesAs a Data Scient...,"[data, security management, python, data analy..."
4,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Chennai,Implementing MLOps practices for model deploym...,"[Artificial Intelligence, Machine Learning, Py..."
5,Data Scientist-Artificial Intelligence,IBM,3.9,5-7 Yrs,Hyderabad,Your role and responsibilitiesAs a Data Scient...,"[data, security management, python, data analy..."
6,Data Scientist-Artificial Intelligence,IBM,3.9,6-7 Yrs,Gurugram,Your role and responsibilitiesAs a Data Scient...,"[data, security management, python, data analy..."
7,Data Scientist-Artificial Intelligence,IBM,3.9,6-8 Yrs,Hyderabad,Your role and responsibilitiesAs a Data Scient...,"[data, security management, python, data analy..."
8,Data Scientist-Artificial Intelligence,IBM,3.9,12-17 Yrs,Hyderabad,Required education . Bachelors Degree . Prefer...,"[data, security management, python, data analy..."
9,Data Scientist-Artificial Intelligence,IBM,3.9,6-8 Yrs,Kolkata,Your role and responsibilitiesAs a Data Scient...,"[data, security management, python, data analy..."
10,Data Scientist-Artificial Intelligence,IBM,3.9,6-8 Yrs,Pune,Your role and responsibilitiesAs a Data Scient...,"[data, security management, python, data analy..."
11,Data Scientist-Artificial Intelligence,IBM,3.9,8-10 Yrs,Gurugram,Your role and responsibilitiesAs a Data Scient...,"[data, security management, python, data analy..."
12,Data Scientist,Optum,4.0,2-7 Yrs,Noida,5+ years of experience delivering Data Analyti...,"[Advanced Analytics, Business Intelligence, Az..."
13,Data Scientist-Artificial Intelligence,IBM,3.9,5-7 Yrs,Pune,Required education . Bachelors Degree . Requir...,"[data, security management, python, data analy..."
14,Data Scientist,Tata Consultancy Services,3.3,10-16 Yrs,"Kolkata, Pune, Chennai",Good team skill and interpersonal skill Experi...,"[Data Science, Vertex Ai, Natural Language Pro..."
15,Data Scientist,Johnson & Johnson,3.9,1-4 Yrs,Gurugram,"Knowledge of model deployment, API integration...","[advanced analytics, aws bedrock, api integrat..."

In [14]:
df.shape

(153, 7)

In [15]:
df.to_csv('naukri_jobs.csv', index=False)

In [2]:
import pandas as pd
data=pd.read_csv('naukri_jobs.csv')
data.head(5)

,title,company,rating,experience,location,description,skills
0,Data Scientist,Kotak Mahindra Bank,3.6,3-7 Yrs,"Mumbai, Bengaluru",Skill requirements: . Masters or Bachelor s De...,"['SAS', 'Machine Learning', 'Analytics', 'Pyth..."
1,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Chennai,Experience in developing and deploying AI / Ge...,"['Data Science', 'Artificial Intelligence', 'M..."
2,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Chennai,Roles and ResponsibilitiesDesign and develop d...,"['Data Science', 'Artificial Intelligence', 'M..."
3,Data Scientist-Artificial Intelligence,IBM,3.9,3-5 Yrs,Kolkata,Your role and responsibilitiesAs a Data Scient...,"['data', 'security management', 'python', 'dat..."
4,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Chennai,Implementing MLOps practices for model deploym...,"['Artificial Intelligence', 'Machine Learning'..."

In [3]:
data[data['company'].str.contains('Tata')]

,title,company,rating,experience,location,description,skills
1,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Chennai,Experience in developing and deploying AI / Ge...,"['Data Science', 'Artificial Intelligence', 'M..."
2,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Chennai,Roles and ResponsibilitiesDesign and develop d...,"['Data Science', 'Artificial Intelligence', 'M..."
4,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Chennai,Implementing MLOps practices for model deploym...,"['Artificial Intelligence', 'Machine Learning'..."
14,Data Scientist,Tata Consultancy Services,3.3,10-16 Yrs,"Kolkata, Pune, Chennai",Good team skill and interpersonal skill Experi...,"['Data Science', 'Vertex Ai', 'Natural Languag..."
17,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Pune,Experience: 6+ Years . Walkin Location: Pune ....,"['generative ai', 'Data Scientist', 'Artificia..."
24,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Bengaluru,Proficiency in programming with Python (prefer...,"['Machine Learning', 'Predictive Modeling', 'P..."
45,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Bengaluru,Proficiency in programming with Python (prefer...,"['Machine Learning', 'Natural Language Process..."
48,Data Scientist,Tata Consultancy Services,3.3,6-8 Yrs,"Hyderabad, Chennai, Bengaluru",AWS Solutions Architect and / or Azure Data Sc...,"['Data Science', 'Pyspark', 'Artificial Intell..."
56,Walk-in || Data Scientist -Walkin_Hyderabad Of...,Tata Consultancy Services,3.3,08 Aug,India,Proficiency in programming with Python (prefer...,"['Data Science', 'Machine Learning', 'Python',..."
57,Tcs Hiring For Data Scientist For Pune Location,Tata Consultancy Services,3.3,6-11 Yrs,Pune,Minimum Qualification: 15 years of full-time e...,"['Data Science', 'Artificial Intelligence', 'N..."
58,Walk-in || Data Scientist-Walkin_TCS Bangalore...,Tata Consultancy Services,3.3,08 Aug,India,Proficiency in programming with Python (prefer...,"['Data Science', 'Machine Learning', 'Python',..."
60,AI ML Data Scientist- Scheduled Face To Face I...,Tata Consultancy Services,3.3,5-10 Yrs,Pune,(Strictly Invite Only) Experience: 6 - 12 Years,"['Data Science', 'generative ai', 'Machine Lea..."
64,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Hyderabad,Proficiency in programming with Python (prefer...,"['Machine Learning', 'Python', 'Natural Langua..."
65,Data Scientist AIML,Tata Consultancy Services,3.3,5-10 Yrs,"Hyderabad, Chennai, Mumbai (All Areas)","Explore, clean, and analyse large, complex dat...","['Artificial Intelligence', 'Machine Learning'..."
104,Data Scientist - 30th July (Thursday) - Virtua...,Tata Consultancy Services,3.3,4-8 Yrs,"Kolkata, Bengaluru",Must Have skills,"['Data Science', 'Natural Language Processing'..."
105,Data Scientist,Tata Consultancy Services,3.3,8-12 Yrs,"Hyderabad, Pune, Bengaluru",Roles and ResponsibilitiesDevelop data-driven ...,"['Artificial Intelligence', 'Machine Learning'..."
112,GenAI Data scientist,Tata Consultancy Services,3.3,5-10 Yrs,"Kolkata, Hyderabad, Bengaluru",Hands-on Experience with API Development and M...,"['Langchain', 'generative ai', 'RAG', 'LLM', '..."
117,Data Scientist AIML,Tata Consultancy Services,3.3,5-10 Yrs,"Chenani, Bengaluru, Delhi / NCR",Expertise in at least one Generative AI and LL...,"['Artificial Intelligence', 'Data Scientist', ..."
118,Data Scientist AIML,Tata Consultancy Services,3.3,5-10 Yrs,"Hyderabad, Bengaluru, Mumbai (All Areas)","Experience with cloud platforms (AWS, Azure, G...","['Data Science', 'Martech', 'Aiml', 'Marketing..."
137,Data Scientist,Tata Consultancy Services,3.3,4-9 Yrs,Pune,Hands-on Experience with API Development and M...,"['generative ai', 'Aiml', 'Machine Learning', ..."
145,Data Scientist -10-12 yr - Delhi,Tata Consultancy Services,3.3,10-12 Yrs,"Noida, New Delhi, Delhi / NCR",Role** Data Scientist Required Technical Skil...,"['Data Science', 'Machine Learning', 'Python',..."

In [4]:
data.value_counts

<bound method DataFrame.value_counts of                                                  title  \
0                                       Data Scientist
1                            Walk-in || Data Scientist
2                            Walk-in || Data Scientist
3               Data Scientist-Artificial Intelligence
4                            Walk-in || Data Scientist
..                                                 ...
148                                     Data Scientist
149                                     Data Scientist
150                                     Data Scientist
151                                     Data Scientist
152  S&C Global Network - AI - Retail - Consultant ...

                       company  rating experience           location  \
0          Kotak Mahindra Bank     3.6    3-7 Yrs  Mumbai, Bengaluru
1    Tata Consultancy Services     3.3     08 Aug            Chennai
2    Tata Consultancy Services     3.3     08 Aug            Chennai
3                          IBM     3.9    3-5 Yrs            Kolkata
4    Tata Consultancy Services     3.3     08 Aug            Chennai
..                         ...     ...        ...                ...
148               WNS Holdings     3.3    6-9 Yrs  Hybrid - Gurugram
149     Ecolab Global Services     3.4    3-5 Yrs          Bengaluru
150     Ecolab Global Services     3.4    3-5 Yrs          Bengaluru
151                        KSB     3.7  10-15 Yrs               Pune
152                  Accenture     3.7    4-9 Yrs           Gurugram

                                           description  \
0    Skill requirements: . Masters or Bachelor s De...
1    Experience in developing and deploying AI / Ge...
2    Roles and ResponsibilitiesDesign and develop d...
3    Your role and responsibilitiesAs a Data Scient...
4    Implementing MLOps practices for model deploym...
..                                                 ...
148  B Tech / M Tech /MCA, masters in computer, Dat...
149  Education / Work Experience: . BS and 3 to 5 y...
150  Education / Work Experience: . BS and 3 to 5 y...
151  Bachelors or Masters degree in Mathematics, Da...
152  We are looking for a skilled professional with...

                                                skills
0    ['SAS', 'Machine Learning', 'Analytics', 'Pyth...
1    ['Data Science', 'Artificial Intelligence', 'M...
2    ['Data Science', 'Artificial Intelligence', 'M...
3    ['data', 'security management', 'python', 'dat...
4    ['Artificial Intelligence', 'Machine Learning'...
..                                                 ...
148  ['Azure Databricks', 'Python', 'SQL', 'Data Sc...
149  ['data Science', 'project management', 'python...
150  ['data scientist', 'project management', 'data...
151  ['Data Science', 'Data Modeling', 'Mathematica...
152  ['machine learning', 'merchandising', 'tensorf...

[153 rows x 7 columns]>

In [5]:
data['experience'].value_counts()

experience
08 Aug       10
8-13 Yrs     10
5-10 Yrs      9
3-8 Yrs       8
1-6 Yrs       7
4-9 Yrs       6
6-11 Yrs      6
3-7 Yrs       6
7-12 Yrs      6
2-7 Yrs       5
3-5 Yrs       5
2-5 Yrs       4
4-6 Yrs       4
6-8 Yrs       4
2-4 Yrs       4
3-6 Yrs       3
8-12 Yrs      3
6-10 Yrs      3
5-7 Yrs       3
1-4 Yrs       3
2-3 Yrs       3
4-8 Yrs       3
3-4 Yrs       2
10-15 Yrs     2
1-3 Yrs       2
2-9 Yrs       2
10-16 Yrs     2
12-17 Yrs     2
5-9 Yrs       2
7-10 Yrs      2
0-3 Yrs       1
2-6 Yrs       1
8-10 Yrs      1
6-7 Yrs       1
4-12 Yrs      1
0-6 Yrs       1
7-11 Yrs      1
9-12 Yrs      1
0-2 Yrs       1
5-8 Yrs       1
0-5 Yrs       1
10-20 Yrs     1
0-4 Yrs       1
10-14 Yrs     1
9-14 Yrs      1
4-7 Yrs       1
4-5 Yrs       1
1-2 Yrs       1
7-8 Yrs       1
1-5 Yrs       1
10-12 Yrs     1
6-9 Yrs       1
Name: count, dtype: int64

In [6]:
data['title'].value_counts()

title
Data Scientist                                                    82
Data Scientist-Artificial Intelligence                             9
Walk-in || Data Scientist                                          8
Data Scientist III                                                 6
Data Scientist I                                                   3
Data Scientist AIML                                                3
Expert Data Scientist                                              3
CoE - Digital Engineering - Data Scientist                         1
Senior/Lead Data Scientist-Gen AI & Classical Machine learning     1
Data Scientist IV                                                  1
Data Scientist - Supply chain                                      1
Data Scientist with R programming                                  1
Machine Learning Engineer / Data Scientist                         1
Sr. Data Scientist - Marketing & Customer Analytics                1
Tcs Hiring For Data Scientist For Pune Location                    1
Walk-in || Data Scientist -Walkin_Hyderabad Office                 1
AI ML Data Scientist- Scheduled Face To Face Interview             1
Walk-in || Data Scientist-Walkin_TCS Bangalore Office              1
Data scientist                                                     1
Lead Gen AI Data Scientist                                         1
Lead Generative AI Data Scientist                                  1
Data Scientist (Machine Learning, Gen AI)                          1
Data Scientist (US Value & Access Insights)                        1
DATA SCIENTIST                                                     1
Data Scientist  Drug Repurposing                                   1
Data Scientist (Commercial)                                        1
Healthcare Data Scientist                                          1
Data Scientist, Actimize                                           1
Data Scientist - 11369                                             1
AO/Data Scientist/Quantitative Researcher                          1
DATA SCIENTIST - Gen AI                                            1
Data Scientist (Maximum notice period should Be 30 days)           1
Data Scientist - 30th July (Thursday) - Virtual Interview          1
GenAI Data scientist                                               1
Finance Data Scientist                                             1
Data Scientist Python Gurobi Linear Optimization | Hyderabad       1
Data Scientist (AI Security)                                       1
Data Scientist-Retail                                              1
Data Scientist - Artificial Intelligence                           1
AI Data Scientist                                                  1
Data Scientist Gas Turbine Service Engineering                     1
Gen AI Data Scientist-AI Labs                                      1
Data Scientist AI/ML                                               1
HCL Hiring Data Scientist                                          1
Data Scientist -10-12 yr - Delhi                                   1
S&C Global Network - AI - Retail - Consultant - Data Scientist     1
Name: count, dtype: int64

In [7]:
data['company'].value_counts()

company
Tata Consultancy Services    21
IBM                           9
Conduent                      7
PwC                           4
Celebal Technologies          4
                             ..
Pjsofttech                    1
Aditya Birla Insulators       1
Apex Group                    1
KSB                           1
Accenture                     1
Name: count, Length: 86, dtype: int64

In [8]:
data.isnull().sum()

title          0
company        0
rating         0
experience     0
location       0
description    0
skills         0
dtype: int64

In [9]:
data.duplicated().sum()

np.int64(0)

In [10]:
data.sample(5)

,title,company,rating,experience,location,description,skills
139,Data Scientist,WNS Holdings,3.3,7-10 Yrs,Hybrid - Gurugram,The ideal candidate will have strong expertise...,"['Agentic Ai', 'Data scientist', 'Natural Lang..."
27,Data Scientist IV,Conduent,3.4,12-17 Yrs,Bengaluru,Job Track Description: Do you enjoy building ...,"['Data Scientist', 'Azure', 'Architecture', 'S..."
31,Data Scientist III,Conduent,3.4,8-13 Yrs,Bangalore Rural,Job Overview We are looking for a Data Enginee...,"['data scientist', 'snowflake', 'data manageme..."
148,Data Scientist,WNS Holdings,3.3,6-9 Yrs,Hybrid - Gurugram,"B Tech / M Tech /MCA, masters in computer, Dat...","['Azure Databricks', 'Python', 'SQL', 'Data Sc..."
16,Sr. Data Scientist - Marketing & Customer Anal...,Hero Fincorp,3.9,0-6 Yrs,Gurugram,Bachelors or Masters degree in Computer Scienc...,"['customer analytics', 'data analysis', 'ai so..."

In [11]:
from ydata_profiling import ProfileReport
profile=ProfileReport(data, title="Pandas Profiling Report", explorative=True)

KeyboardInterrupt:

In [30]:
profile.to_file("EDA_Report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 7/7 [00:03<00:00,  1.90it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [12]:
data.isnull().sum()

title          0
company        0
rating         0
experience     0
location       0
description    0
skills         0
dtype: int64

In [13]:
data.duplicated().sum()

np.int64(0)

In [14]:
data.sample(2)

,title,company,rating,experience,location,description,skills
113,Data Scientist,Dun & Bradstreet,3.2,2-5 Yrs,Chennai,The ideal candidate will have strong hands on ...,"['Pyspark', 'Evaluation', 'System Design', 'Ar..."
67,Lead Generative AI Data Scientist,Net Connect,3.1,3-6 Yrs,"Pune, Gurugram, Bengaluru","Proficiency in cloud platforms such as Azure, ...","['Artificial Intelligence', 'Natural Language ..."

In [15]:
data['title'].value_counts()

title
Data Scientist                                                    82
Data Scientist-Artificial Intelligence                             9
Walk-in || Data Scientist                                          8
Data Scientist III                                                 6
Data Scientist I                                                   3
Data Scientist AIML                                                3
Expert Data Scientist                                              3
CoE - Digital Engineering - Data Scientist                         1
Senior/Lead Data Scientist-Gen AI & Classical Machine learning     1
Data Scientist IV                                                  1
Data Scientist - Supply chain                                      1
Data Scientist with R programming                                  1
Machine Learning Engineer / Data Scientist                         1
Sr. Data Scientist - Marketing & Customer Analytics                1
Tcs Hiring For Data Scientist For Pune Location                    1
Walk-in || Data Scientist -Walkin_Hyderabad Office                 1
AI ML Data Scientist- Scheduled Face To Face Interview             1
Walk-in || Data Scientist-Walkin_TCS Bangalore Office              1
Data scientist                                                     1
Lead Gen AI Data Scientist                                         1
Lead Generative AI Data Scientist                                  1
Data Scientist (Machine Learning, Gen AI)                          1
Data Scientist (US Value & Access Insights)                        1
DATA SCIENTIST                                                     1
Data Scientist  Drug Repurposing                                   1
Data Scientist (Commercial)                                        1
Healthcare Data Scientist                                          1
Data Scientist, Actimize                                           1
Data Scientist - 11369                                             1
AO/Data Scientist/Quantitative Researcher                          1
DATA SCIENTIST - Gen AI                                            1
Data Scientist (Maximum notice period should Be 30 days)           1
Data Scientist - 30th July (Thursday) - Virtual Interview          1
GenAI Data scientist                                               1
Finance Data Scientist                                             1
Data Scientist Python Gurobi Linear Optimization | Hyderabad       1
Data Scientist (AI Security)                                       1
Data Scientist-Retail                                              1
Data Scientist - Artificial Intelligence                           1
AI Data Scientist                                                  1
Data Scientist Gas Turbine Service Engineering                     1
Gen AI Data Scientist-AI Labs                                      1
Data Scientist AI/ML                                               1
HCL Hiring Data Scientist                                          1
Data Scientist -10-12 yr - Delhi                                   1
S&C Global Network - AI - Retail - Consultant - Data Scientist     1
Name: count, dtype: int64

In [16]:
data['company'].value_counts()

company
Tata Consultancy Services    21
IBM                           9
Conduent                      7
PwC                           4
Celebal Technologies          4
                             ..
Pjsofttech                    1
Aditya Birla Insulators       1
Apex Group                    1
KSB                           1
Accenture                     1
Name: count, Length: 86, dtype: int64

In [17]:
data['experience'].value_counts()

experience
08 Aug       10
8-13 Yrs     10
5-10 Yrs      9
3-8 Yrs       8
1-6 Yrs       7
4-9 Yrs       6
6-11 Yrs      6
3-7 Yrs       6
7-12 Yrs      6
2-7 Yrs       5
3-5 Yrs       5
2-5 Yrs       4
4-6 Yrs       4
6-8 Yrs       4
2-4 Yrs       4
3-6 Yrs       3
8-12 Yrs      3
6-10 Yrs      3
5-7 Yrs       3
1-4 Yrs       3
2-3 Yrs       3
4-8 Yrs       3
3-4 Yrs       2
10-15 Yrs     2
1-3 Yrs       2
2-9 Yrs       2
10-16 Yrs     2
12-17 Yrs     2
5-9 Yrs       2
7-10 Yrs      2
0-3 Yrs       1
2-6 Yrs       1
8-10 Yrs      1
6-7 Yrs       1
4-12 Yrs      1
0-6 Yrs       1
7-11 Yrs      1
9-12 Yrs      1
0-2 Yrs       1
5-8 Yrs       1
0-5 Yrs       1
10-20 Yrs     1
0-4 Yrs       1
10-14 Yrs     1
9-14 Yrs      1
4-7 Yrs       1
4-5 Yrs       1
1-2 Yrs       1
7-8 Yrs       1
1-5 Yrs       1
10-12 Yrs     1
6-9 Yrs       1
Name: count, dtype: int64

In [18]:
data['location'].value_counts()

location
Bengaluru                                        37
Pune                                             17
Hyderabad                                        16
Chennai                                          11
Gurugram                                          8
Hybrid - Bengaluru                                5
Mumbai                                            4
Hybrid - Hyderabad, Gurugram, Bengaluru           3
Hybrid - Pune                                     3
Ahmedabad                                         3
Bangalore Rural                                   2
Hyderabad, Pune, Bengaluru                        2
Remote                                            2
Kolkata                                           2
Noida                                             2
Hybrid - Gurugram                                 2
Mumbai (All Areas)                                2
Hybrid - Hyderabad, Pune, Bengaluru               2
India                                             2
Kolkata, Pune, Chennai                            1
Mumbai, Bengaluru                                 1
Hybrid - Pune, Chennai, Bengaluru                 1
Hybrid - India                                    1
Pune, Gurugram, Bengaluru                         1
Hyderabad, Chennai, Mumbai (All Areas)            1
Hybrid - Pune, Chennai                            1
Hybrid - Chennai                                  1
Ahmedabad(Gota)                                   1
Hyderabad, Chennai                                1
Hybrid - Chennai, Bengaluru                       1
Hyderabad, Chennai, Bengaluru                     1
Hybrid - Noida, Chennai                           1
Hybrid - Mumbai (All Areas)                       1
Coimbatore                                        1
Nagercoil                                         1
Hybrid - Bangalore Rural, Gurugram, Bengaluru     1
Kolkata, Bengaluru                                1
Hybrid - Pune, Bengaluru, Delhi / NCR             1
Jaipur                                            1
Kolkata, Hyderabad, Bengaluru                     1
Hybrid - Hyderabad                                1
Hyderabad, Bengaluru, Mumbai (All Areas)          1
Chenani, Bengaluru, Delhi / NCR                   1
Noida, Hyderabad, Bengaluru                       1
New Delhi                                         1
Hybrid - Hyderabad, Pune, Mumbai (All Areas)      1
Noida, New Delhi, Delhi / NCR                     1
Name: count, dtype: int64

In [19]:
data['location'].value_counts()

location
Bengaluru                                        37
Pune                                             17
Hyderabad                                        16
Chennai                                          11
Gurugram                                          8
Hybrid - Bengaluru                                5
Mumbai                                            4
Hybrid - Hyderabad, Gurugram, Bengaluru           3
Hybrid - Pune                                     3
Ahmedabad                                         3
Bangalore Rural                                   2
Hyderabad, Pune, Bengaluru                        2
Remote                                            2
Kolkata                                           2
Noida                                             2
Hybrid - Gurugram                                 2
Mumbai (All Areas)                                2
Hybrid - Hyderabad, Pune, Bengaluru               2
India                                             2
Kolkata, Pune, Chennai                            1
Mumbai, Bengaluru                                 1
Hybrid - Pune, Chennai, Bengaluru                 1
Hybrid - India                                    1
Pune, Gurugram, Bengaluru                         1
Hyderabad, Chennai, Mumbai (All Areas)            1
Hybrid - Pune, Chennai                            1
Hybrid - Chennai                                  1
Ahmedabad(Gota)                                   1
Hyderabad, Chennai                                1
Hybrid - Chennai, Bengaluru                       1
Hyderabad, Chennai, Bengaluru                     1
Hybrid - Noida, Chennai                           1
Hybrid - Mumbai (All Areas)                       1
Coimbatore                                        1
Nagercoil                                         1
Hybrid - Bangalore Rural, Gurugram, Bengaluru     1
Kolkata, Bengaluru                                1
Hybrid - Pune, Bengaluru, Delhi / NCR             1
Jaipur                                            1
Kolkata, Hyderabad, Bengaluru                     1
Hybrid - Hyderabad                                1
Hyderabad, Bengaluru, Mumbai (All Areas)          1
Chenani, Bengaluru, Delhi / NCR                   1
Noida, Hyderabad, Bengaluru                       1
New Delhi                                         1
Hybrid - Hyderabad, Pune, Mumbai (All Areas)      1
Noida, New Delhi, Delhi / NCR                     1
Name: count, dtype: int64

In [20]:
data['location'].isnull().sum()

np.int64(0)

first of all let's start with title column

In [21]:
data['title'].str.startswith(" ").sum()

np.int64(0)

In [22]:
data['title'].str.endswith(" ").sum()

np.int64(0)

In [23]:
data['title'].str.startswith(" ").sum()

np.int64(0)

In [24]:
print(data['title'].nunique())

46

In [25]:
(data["title"] == "").sum()

np.int64(0)

In [26]:
data["title"].sample(10)

94             AO/Data Scientist/Quantitative Researcher
7                 Data Scientist-Artificial Intelligence
71                                        DATA SCIENTIST
96                             Walk-in || Data Scientist
116    Data Scientist Python Gurobi Linear Optimizati...
44                                        Data Scientist
84                                        Data Scientist
19                                        Data Scientist
32                                    Data Scientist III
16     Sr. Data Scientist - Marketing & Customer Anal...
Name: title, dtype: object

In [27]:
data["title"] = data["title"].str.strip()

the title coulmn seems to be cleaned 

so let's focus on "company" column

In [28]:
data['company'].isnull().sum()

np.int64(0)

In [29]:
data["company"].str.startswith(" ").sum()

np.int64(0)

In [30]:
data["company"].str.endswith(" ").sum()

np.int64(0)

In [31]:
(data["company"] == "").sum()

np.int64(0)

In [32]:
data['company'].nunique()

86

In [33]:
data["company"].sample(10)

27                  Conduent
41                    Zageno
124    Brigosha Technologies
101                  Siemens
59                        EY
122                     Ford
96                MKS Vision
114           Hitachi Energy
146                  HCLTech
63                   Infosys
Name: company, dtype: object

In [34]:
data["company"].value_counts().head(15)

company
Tata Consultancy Services      21
IBM                             9
Conduent                        7
PwC                             4
Celebal Technologies            4
Ford                            4
LTM                             4
Amgen Inc                       4
Genpact                         4
Ciklum                          3
Wabtec                          3
Altimetrik                      2
Aon                             2
Happiest Minds Technologies     2
Net Connect                     2
Name: count, dtype: int64

In [35]:
##for rating
data['rating'].isnull().sum()

np.int64(0)

In [36]:
data["rating"].dtype

dtype('float64')

In [37]:
data["rating"].sample(10)

14     3.3
140    3.7
10     3.9
109    3.6
133    4.0
92     3.2
107    3.8
2      3.3
22     4.0
61     4.3
Name: rating, dtype: float64

In [38]:
data["rating"].describe()

count    153.000000
mean       3.533333
std        0.424264
min        2.000000
25%        3.300000
50%        3.500000
75%        3.900000
max        4.800000
Name: rating, dtype: float64

In [39]:
data["rating"].value_counts().head(10)

rating
3.3    30
3.4    20
3.6    18
3.9    15
4.0    12
3.8     9
3.5     7
3.7     7
2.9     7
4.1     7
Name: count, dtype: int64

In [40]:
##for experience
data['experience'].isnull().sum()

np.int64(0)

In [41]:
data['experience'].dtype

dtype('O')

In [42]:
data['experience'].value_counts()

experience
08 Aug       10
8-13 Yrs     10
5-10 Yrs      9
3-8 Yrs       8
1-6 Yrs       7
4-9 Yrs       6
6-11 Yrs      6
3-7 Yrs       6
7-12 Yrs      6
2-7 Yrs       5
3-5 Yrs       5
2-5 Yrs       4
4-6 Yrs       4
6-8 Yrs       4
2-4 Yrs       4
3-6 Yrs       3
8-12 Yrs      3
6-10 Yrs      3
5-7 Yrs       3
1-4 Yrs       3
2-3 Yrs       3
4-8 Yrs       3
3-4 Yrs       2
10-15 Yrs     2
1-3 Yrs       2
2-9 Yrs       2
10-16 Yrs     2
12-17 Yrs     2
5-9 Yrs       2
7-10 Yrs      2
0-3 Yrs       1
2-6 Yrs       1
8-10 Yrs      1
6-7 Yrs       1
4-12 Yrs      1
0-6 Yrs       1
7-11 Yrs      1
9-12 Yrs      1
0-2 Yrs       1
5-8 Yrs       1
0-5 Yrs       1
10-20 Yrs     1
0-4 Yrs       1
10-14 Yrs     1
9-14 Yrs      1
4-7 Yrs       1
4-5 Yrs       1
1-2 Yrs       1
7-8 Yrs       1
1-5 Yrs       1
10-12 Yrs     1
6-9 Yrs       1
Name: count, dtype: int64

In [43]:
data['experience'].nunique()

52

In [44]:
data['experience'].dtype

dtype('O')

In [45]:
data["min_experience"] = data["experience"].str.extract(r"(\d+)-")[0].astype(float)
data["max_experience"] = data["experience"].str.extract(r"-(\d+)")[0].astype(float)

In [46]:
data["avg_experience"] = (data["min_experience"]+data["max_experience"])/2

In [47]:
data[data["min_experience"].isna()][["experience"]]

   experience
1      08 Aug
2      08 Aug
4      08 Aug
17     08 Aug
24     08 Aug
45     08 Aug
56     08 Aug
58     08 Aug
64     08 Aug
96     08 Aug

In [48]:
import numpy as np
data.loc[data["experience"] == "08 Aug", ["min_experience", "max_experience", "avg_experience"]] = np.nan

In [49]:
def categorize_experience(x):
    if pd.isna(x):
        return np.nan
    elif x <= 2.5:
        return "Beginner"
    elif x <= 6:
        return "Intermediate"
    else:
        return "Advanced"

In [50]:
data["experience_level"] = data["avg_experience"].apply(categorize_experience)

In [51]:
data[[
    "experience",
    "min_experience",
    "max_experience",
    "avg_experience",
    "experience_level"
]].head(20)

   experience  min_experience  max_experience  avg_experience experience_level
0     3-7 Yrs             3.0             7.0             5.0     Intermediate
1      08 Aug             NaN             NaN             NaN              NaN
2      08 Aug             NaN             NaN             NaN              NaN
3     3-5 Yrs             3.0             5.0             4.0     Intermediate
4      08 Aug             NaN             NaN             NaN              NaN
5     5-7 Yrs             5.0             7.0             6.0     Intermediate
6     6-7 Yrs             6.0             7.0             6.5         Advanced
7     6-8 Yrs             6.0             8.0             7.0         Advanced
8   12-17 Yrs            12.0            17.0            14.5         Advanced
9     6-8 Yrs             6.0             8.0             7.0         Advanced
10    6-8 Yrs             6.0             8.0             7.0         Advanced
11   8-10 Yrs             8.0            10.0             9.0         Advanced
12    2-7 Yrs             2.0             7.0             4.5     Intermediate
13    5-7 Yrs             5.0             7.0             6.0     Intermediate
14  10-16 Yrs            10.0            16.0            13.0         Advanced
15    1-4 Yrs             1.0             4.0             2.5         Beginner
16    0-6 Yrs             0.0             6.0             3.0     Intermediate
17     08 Aug             NaN             NaN             NaN              NaN
18    2-5 Yrs             2.0             5.0             3.5     Intermediate
19   4-12 Yrs             4.0            12.0             8.0         Advanced

In [52]:
data["experience_level"].value_counts(dropna=False)

experience_level
Advanced        69
Intermediate    61
Beginner        13
NaN             10
Name: count, dtype: int64

In [53]:
data['experience_level'].replace("NaN",np.nan)

0      Intermediate
1               NaN
2               NaN
3      Intermediate
4               NaN
           ...
148        Advanced
149    Intermediate
150    Intermediate
151        Advanced
152        Advanced
Name: experience_level, Length: 153, dtype: object

In [54]:
data['experience_level'].value_counts()

experience_level
Advanced        69
Intermediate    61
Beginner        13
Name: count, dtype: int64

In [55]:
data.head(5)

,title,company,rating,experience,location,description,skills,min_experience,max_experience,avg_experience,experience_level
0,Data Scientist,Kotak Mahindra Bank,3.6,3-7 Yrs,"Mumbai, Bengaluru",Skill requirements: . Masters or Bachelor s De...,"['SAS', 'Machine Learning', 'Analytics', 'Pyth...",3.0,7.0,5.0,Intermediate
1,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Chennai,Experience in developing and deploying AI / Ge...,"['Data Science', 'Artificial Intelligence', 'M...",NaN,NaN,NaN,NaN
2,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Chennai,Roles and ResponsibilitiesDesign and develop d...,"['Data Science', 'Artificial Intelligence', 'M...",NaN,NaN,NaN,NaN
3,Data Scientist-Artificial Intelligence,IBM,3.9,3-5 Yrs,Kolkata,Your role and responsibilitiesAs a Data Scient...,"['data', 'security management', 'python', 'dat...",3.0,5.0,4.0,Intermediate
4,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Chennai,Implementing MLOps practices for model deploym...,"['Artificial Intelligence', 'Machine Learning'...",NaN,NaN,NaN,NaN

In [56]:
data['location'].isnull().sum()

np.int64(0)

In [57]:
data['location'].duplicated().sum()

np.int64(106)

In [58]:
data['location'].nunique()

47

In [59]:
data['location'].shape

(153,)

In [60]:
(data["location"] == "").sum()

np.int64(0)

In [61]:
data["location"].str.startswith(" ").sum()

np.int64(0)

In [62]:
data["location"].str.endswith(" ").sum()

np.int64(0)

In [63]:
data["location"] = data["location"].str.strip()

In [64]:
data["location"] = data["location"].str.replace(r"\s+", " ", regex=True)

In [65]:
data["location"] = data["location"].str.title()

In [66]:
data['location'].value_counts()

location
Bengaluru                                        37
Pune                                             17
Hyderabad                                        16
Chennai                                          11
Gurugram                                          8
Hybrid - Bengaluru                                5
Mumbai                                            4
Hybrid - Hyderabad, Gurugram, Bengaluru           3
Hybrid - Pune                                     3
Ahmedabad                                         3
Bangalore Rural                                   2
Hyderabad, Pune, Bengaluru                        2
Remote                                            2
Kolkata                                           2
Noida                                             2
Hybrid - Gurugram                                 2
Mumbai (All Areas)                                2
Hybrid - Hyderabad, Pune, Bengaluru               2
India                                             2
Kolkata, Pune, Chennai                            1
Mumbai, Bengaluru                                 1
Hybrid - Pune, Chennai, Bengaluru                 1
Hybrid - India                                    1
Pune, Gurugram, Bengaluru                         1
Hyderabad, Chennai, Mumbai (All Areas)            1
Hybrid - Pune, Chennai                            1
Hybrid - Chennai                                  1
Ahmedabad(Gota)                                   1
Hyderabad, Chennai                                1
Hybrid - Chennai, Bengaluru                       1
Hyderabad, Chennai, Bengaluru                     1
Hybrid - Noida, Chennai                           1
Hybrid - Mumbai (All Areas)                       1
Coimbatore                                        1
Nagercoil                                         1
Hybrid - Bangalore Rural, Gurugram, Bengaluru     1
Kolkata, Bengaluru                                1
Hybrid - Pune, Bengaluru, Delhi / Ncr             1
Jaipur                                            1
Kolkata, Hyderabad, Bengaluru                     1
Hybrid - Hyderabad                                1
Hyderabad, Bengaluru, Mumbai (All Areas)          1
Chenani, Bengaluru, Delhi / Ncr                   1
Noida, Hyderabad, Bengaluru                       1
New Delhi                                         1
Hybrid - Hyderabad, Pune, Mumbai (All Areas)      1
Noida, New Delhi, Delhi / Ncr                     1
Name: count, dtype: int64

In [67]:
data['location'].head(30)

0          Mumbai, Bengaluru
1                    Chennai
2                    Chennai
3                    Kolkata
4                    Chennai
5                  Hyderabad
6                   Gurugram
7                  Hyderabad
8                  Hyderabad
9                    Kolkata
10                      Pune
11                  Gurugram
12                     Noida
13                      Pune
14    Kolkata, Pune, Chennai
15                  Gurugram
16                  Gurugram
17                      Pune
18                 Bengaluru
19                 Bengaluru
20                  Gurugram
21                    Mumbai
22                 Bengaluru
23                 Bengaluru
24                 Bengaluru
25                   Chennai
26        Hybrid - Bengaluru
27                 Bengaluru
28        Hybrid - Bengaluru
29                    Remote
Name: location, dtype: object

In [68]:
data["location_clean"] = data["location"].str.replace(
    r"^Hybrid\s*-\s*", "", regex=True
)

In [69]:
data["location_clean"] = data["location_clean"].replace({
    "Bangalore": "Bengaluru",
    "New Delhi": "Delhi",
    "Mumbai (All Areas)": "Mumbai"
})

In [70]:
data["location_list"] = data["location_clean"].str.split(",")

In [71]:
data['location_clean'].shape

(153,)

In [72]:
data['skills'].isnull().sum()

np.int64(0)

In [73]:
data["skills"].sample(10)

151    ['Data Science', 'Data Modeling', 'Mathematica...
0      ['SAS', 'Machine Learning', 'Analytics', 'Pyth...
67     ['Artificial Intelligence', 'Natural Language ...
89     ['Logistic Regression', 'Problem Solving', 'Pr...
107    ['Automation', 'Payment processing', 'ISO', 'T...
141    ['Data scientist', 'Time Series', 'Machine Lea...
47     ['Cloud', 'Machine Learning', 'Python', 'SQL',...
94     ['Data analysis', 'MS SQL', 'Financial stateme...
113    ['Pyspark', 'Evaluation', 'System Design', 'Ar...
115    ['Ai', 'Leadership', 'Azure', 'Cloud Platform'...
Name: skills, dtype: object

In [74]:
data["skills"].apply(type).value_counts()

skills
<class 'str'>    153
Name: count, dtype: int64

In [75]:
data["skills"].apply(len).describe()

count    153.000000
mean     125.058824
std       21.505885
min       66.000000
25%      115.000000
50%      126.000000
75%      139.000000
max      192.000000
Name: skills, dtype: float64

In [76]:
(data["skills"].apply(len) == 0).sum()

np.int64(0)

In [77]:
import ast

data["skills"] = data["skills"].apply(ast.literal_eval)

In [78]:
data["skills"].apply(type).value_counts()

skills
<class 'list'>    153
Name: count, dtype: int64

In [79]:
data["skills"].apply(len).describe()

count    153.000000
mean       7.862745
std        0.445132
min        6.000000
25%        8.000000
50%        8.000000
75%        8.000000
max        8.000000
Name: skills, dtype: float64

In [80]:
(data["skills"].apply(len) == 0).sum()

np.int64(0)

In [81]:
# Remove extra whitespace from each skill
data["skills"] = data["skills"].apply(
    lambda skills: [skill.strip() for skill in skills]
)

# Remove duplicate skills within each job
data["skills"] = data["skills"].apply(
    lambda skills: list(dict.fromkeys(skills))
)

In [82]:
data['skills'].head(10)

0    [SAS, Machine Learning, Analytics, Python, SQL...
1    [Data Science, Artificial Intelligence, Machin...
2    [Data Science, Artificial Intelligence, Machin...
3    [data, security management, python, data analy...
4    [Artificial Intelligence, Machine Learning, Py...
5    [data, security management, python, data analy...
6    [data, security management, python, data analy...
7    [data, security management, python, data analy...
8    [data, security management, python, data analy...
9    [data, security management, python, data analy...
Name: skills, dtype: object

In [83]:
data["skills"] = data["skills"].apply(
    lambda skills: [skill.strip().lower() for skill in skills]
)

In [84]:
data['skills'].head(10)

0    [sas, machine learning, analytics, python, sql...
1    [data science, artificial intelligence, machin...
2    [data science, artificial intelligence, machin...
3    [data, security management, python, data analy...
4    [artificial intelligence, machine learning, py...
5    [data, security management, python, data analy...
6    [data, security management, python, data analy...
7    [data, security management, python, data analy...
8    [data, security management, python, data analy...
9    [data, security management, python, data analy...
Name: skills, dtype: object

In [85]:
data["skills"] = data["skills"].apply(
    lambda skills: list(dict.fromkeys(skills))
)

In [86]:
data['skills'].head(10)

0    [sas, machine learning, analytics, python, sql...
1    [data science, artificial intelligence, machin...
2    [data science, artificial intelligence, machin...
3    [data, security management, python, data analy...
4    [artificial intelligence, machine learning, py...
5    [data, security management, python, data analy...
6    [data, security management, python, data analy...
7    [data, security management, python, data analy...
8    [data, security management, python, data analy...
9    [data, security management, python, data analy...
Name: skills, dtype: object

In [87]:
data['description'].isnull().sum()

np.int64(0)

In [88]:
data['description'].dtype

dtype('O')

In [89]:
data['description'].sample(5)

10     Your role and responsibilitiesAs a Data Scient...
129    Data Scientist Forecasting & Predictive Analyt...
120    Key Elements . We are looking for the followin...
20     Bachelors / masters in computer science, Engin...
23     Expert-level proficiency in SQL and experience...
Name: description, dtype: object

In [90]:
data['description'].str.len().describe()

count    153.000000
mean      88.372549
std        7.696447
min       16.000000
25%       90.000000
50%       90.000000
75%       90.000000
max       90.000000
Name: description, dtype: float64

In [91]:
(data["description"].str.strip() == "").sum()

np.int64(0)

In [92]:
data['description'] = data['description'].str.strip()

In [93]:
data["description"] = data["description"].str.replace(
    r"\s+", " ", regex=True
)

In [94]:
data['description'].duplicated().sum()

np.int64(17)

In [95]:
data[data["description"].duplicated(keep=False)]["description"].value_counts()

description
Your role and responsibilitiesAs a Data Scientist with expertise in Artificial Intellig...    7
Proficiency in programming with Python (preferred) or R for data analysis and model dev...    5
Job Overview We are looking for a Data Engineer who will be part of our Analytics Pract...    2
- At least a Bachelors degree What You Must Have At least 8 years of experience               2
Job Overview We are looking for a BI & Visualization Developer who will be part of ou...      2
Ciklum is looking for an Expert Data Scientist to join our team full-time in India.We a...    2
We are looking for a highly motivated Data Scientist with 7+ years of experience t...         2
What You Must Have. - At least a Bachelors degreeHaving understanding of working on thi...    2
Education / Work Experience: . BS and 3 to 5 years related experience or MS and less th...    2
Name: count, dtype: int64

In [98]:
print("Duplicate descriptions:", data["description"].duplicated().sum())

Duplicate descriptions: 17

In [101]:
data.head(12)

,title,company,rating,experience,location,description,skills,min_experience,max_experience,avg_experience,experience_level,location_clean,location_list
0,Data Scientist,Kotak Mahindra Bank,3.6,3-7 Yrs,"Mumbai, Bengaluru",Skill requirements: . Masters or Bachelor s De...,"[sas, machine learning, analytics, python, sql...",3.0,7.0,5.0,Intermediate,"Mumbai, Bengaluru","[Mumbai, Bengaluru]"
1,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Chennai,Experience in developing and deploying AI / Ge...,"[data science, artificial intelligence, machin...",NaN,NaN,NaN,NaN,Chennai,[Chennai]
2,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Chennai,Roles and ResponsibilitiesDesign and develop d...,"[data science, artificial intelligence, machin...",NaN,NaN,NaN,NaN,Chennai,[Chennai]
3,Data Scientist-Artificial Intelligence,IBM,3.9,3-5 Yrs,Kolkata,Your role and responsibilitiesAs a Data Scient...,"[data, security management, python, data analy...",3.0,5.0,4.0,Intermediate,Kolkata,[Kolkata]
4,Walk-in || Data Scientist,Tata Consultancy Services,3.3,08 Aug,Chennai,Implementing MLOps practices for model deploym...,"[artificial intelligence, machine learning, py...",NaN,NaN,NaN,NaN,Chennai,[Chennai]
5,Data Scientist-Artificial Intelligence,IBM,3.9,5-7 Yrs,Hyderabad,Your role and responsibilitiesAs a Data Scient...,"[data, security management, python, data analy...",5.0,7.0,6.0,Intermediate,Hyderabad,[Hyderabad]
6,Data Scientist-Artificial Intelligence,IBM,3.9,6-7 Yrs,Gurugram,Your role and responsibilitiesAs a Data Scient...,"[data, security management, python, data analy...",6.0,7.0,6.5,Advanced,Gurugram,[Gurugram]
7,Data Scientist-Artificial Intelligence,IBM,3.9,6-8 Yrs,Hyderabad,Your role and responsibilitiesAs a Data Scient...,"[data, security management, python, data analy...",6.0,8.0,7.0,Advanced,Hyderabad,[Hyderabad]
8,Data Scientist-Artificial Intelligence,IBM,3.9,12-17 Yrs,Hyderabad,Required education . Bachelors Degree . Prefer...,"[data, security management, python, data analy...",12.0,17.0,14.5,Advanced,Hyderabad,[Hyderabad]
9,Data Scientist-Artificial Intelligence,IBM,3.9,6-8 Yrs,Kolkata,Your role and responsibilitiesAs a Data Scient...,"[data, security management, python, data analy...",6.0,8.0,7.0,Advanced,Kolkata,[Kolkata]
10,Data Scientist-Artificial Intelligence,IBM,3.9,6-8 Yrs,Pune,Your role and responsibilitiesAs a Data Scient...,"[data, security management, python, data analy...",6.0,8.0,7.0,Advanced,Pune,[Pune]
11,Data Scientist-Artificial Intelligence,IBM,3.9,8-10 Yrs,Gurugram,Your role and responsibilitiesAs a Data Scient...,"[data, security management, python, data analy...",8.0,10.0,9.0,Advanced,Gurugram,[Gurugram]

In [102]:
data.isnull().sum()

title                0
company              0
rating               0
experience           0
location             0
description          0
skills               0
min_experience      10
max_experience      10
avg_experience      10
experience_level    10
location_clean       0
location_list        0
dtype: int64

In [103]:
data.dtypes

title                object
company              object
rating              float64
experience           object
location             object
description          object
skills               object
min_experience      float64
max_experience      float64
avg_experience      float64
experience_level     object
location_clean       object
location_list        object
dtype: object

In [104]:
data.shape

(153, 13)

In [105]:
data.drop(columns=["skills", "location_list"]).duplicated().sum()

np.int64(2)

In [106]:
for i in data.columns:
    print(data[i].duplicated().sum())

107
67
132
101
106
17
14
140
135
125
149
115
115

In [107]:
data.to_csv('naukri_jobs_cleaned.csv', index=False)